### ISSUE TITLE
MacOS: Ability to remove menu bar icon?

### ISSUE THREAD

**Issue by conformist1** [jerrod-lankford/google-voice-desktop-app#33]
Would appreciate knowing if this is something I missed or a feature that could be added.

Thank you!!!!

**Comment by jerrod-lankford** [comment]
Its not that I couldn't add an option or something but it changes how the close action works, since it no longer minimizes to the tray / menu bar. Its some amount of work for pretty small benefit, so i probably wouldn't do it unless it was heavily requested. Im trying to clean up issues so im going to close this for now.
