### ISSUE TITLE
Taskbar Notifications on Windows With Small Taskbar Icons Enabled Don't Work

### ISSUE THREAD

**Issue by wickedfable** [jerrod-lankford/google-voice-desktop-app#37]
I noticed there is no notification number or at least a flashing icon if you have a Windows taskbar with the "Small Taskbar Icons" option enabled.

To replicate:
1. Right-click taskbar and select "Taskbar settings"
2. Enable "Use small taskbar buttons" option
3. Receive a message or call and see that notifications no longer appear

From what I can see of other apps, it might not be standard or possible to include a notification count in the icon but usually other apps will have the taskbar button flash when a new message has arrived. I think this would be a great functionality for this awesome app.

**Comment by dahainsworth** [comment]
first thanks to the authors for this app.  hangouts was like the perfect sms app for me for years.   this issue is the singular thing making this less useful than hangouts.  ill attach two images with large and small icons.   with small icons if you miss the notification popup there is no way to see something came it.  hoping it may be simple to highlight the icon like hangouts does.
![large_icons](https://user-images.githubusercontent.com/32576442/114316477-bd515b00-9ad1-11eb-87ff-f60c829c261c.PNG)
![small_icons](https://user-images.githubusercontent.com/32576442/114316480-c0e4e200-9ad1-11eb-869a-999c2e051a61.PNG)

**Comment by eFail** [comment]
@dahainsworth, here you go :)
https://github.com/jerrod-lankford/google-voice-desktop-app/pull/81

**Comment by dahainsworth** [comment]
upgraded to latest release.
with small icons enabled i get a notification popup as normal,  the icon flashes and stays lit until i open the app again
thank you thank you thank you. 
i believe this issue can be resolved.
![image](https://user-images.githubusercontent.com/32576442/133150172-0e2ffef2-2954-4d51-b1de-3ae5ae0b3b44.png)

**Comment by eFail** [comment]
@jerrod-lankford You can now mark this one as complete.
